### ISSUE TITLE
Mark notifications as read isn't working

### ISSUE THREAD

**Issue by m1guelpf** [KnpLabs/php-github-api#493]
```
[2016-12-23 18:42:05] local.ERROR: Github\Exception\ErrorException: Problems parsing JSON in /home/m1guelpiedrafita/www/github/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:51
Stack trace:
#0 /home/m1guelpiedrafita/www/github/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Github\HttpClient\Plugin\GithubExceptionThrower->Github\HttpClient\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 /home/m1guelpiedrafita/www/github/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php(88): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#2 /home/m1guelpiedrafita/www/github/vendor/php-http/client-common/src/PluginClient.php(156): Github\HttpClient\Plugin\GithubExceptionThrower->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#3 /home/m1guelpiedrafita/www/github/vendor/php-http/client-common/src/PluginClient.php(170): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#4 /home/m1guelpiedrafita/www/github/vendor/php-http/client-common/src/PluginClient.php(87): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 /home/m1guelpiedrafita/www/github/vendor/php-http/client-common/src/HttpMethodsClient.php(203): Http\Client\Common\PluginClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#6 /home/m1guelpiedrafita/www/github/vendor/php-http/client-common/src/HttpMethodsClient.php(188): Http\Client\Common\HttpMethodsClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#7 /home/m1guelpiedrafita/www/github/vendor/php-http/client-common/src/HttpMethodsClient.php(123): Http\Client\Common\HttpMethodsClient->send('PUT', '/notifications', Array, NULL)
#8 /home/m1guelpiedrafita/www/github/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php(178): Http\Client\Common\HttpMethodsClient->put('/notifications', Array, NULL)
#9 /home/m1guelpiedrafita/www/github/vendor/knplabs/github-api/lib/Github/Api/Notification.php(58): Github\Api\AbstractApi->put('/notifications', Array)
#10 /home/m1guelpiedrafita/www/github/app/Http/Controllers/GithubController.php(91): Github\Api\Notification->markRead()
#11 [internal function]: App\Http\Controllers\GithubController::markAllRead()
#12 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#13 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('markAllRead', Array)
#14 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\GithubController), 'markAllRead')
#15 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#16 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#42 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#43 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#44 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#45 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 /home/m1guelpiedrafita/www/github/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 /home/m1guelpiedrafita/www/github/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main}  
```

**Comment by m1guelpf** [comment]
Any updates on this?
I need this feature!

**Comment by Nyholm** [comment]
Can you debug this a bit more? How come it is not working? What should be done in order to fix it?

**Comment by GrahamCampbell** [comment]
I think this can be closed. I use this endpoint every day, and it is working fine, when called correctly.

**Comment by acrobat** [comment]
Thanks for the feedback @GrahamCampbell, closing this issue!
